'use client'
import './globals.css'
import { Navbar } from './components/Navbar'

import { ThemeProvider } from 'next-themes'

import { Inter } from 'next/font/google'

const inter = Inter({ weight: ['600'], subsets: ['latin']})

// Disable due to use client and ThemeProvided - bugfix later
// export const metadata = {
//   title: 'Syukran | Backend Developer',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <ThemeProvider enableSystem={true} attribute='class'>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
